import {
  TDepthDayGraph,
  TCalendarBalanceTime,
} from '../reducers/typesReportsReducer'
export const SET_DAY_SUMMARY = 'SET_DAY_SUMMARY'
type SET_DAY_SUMMARY_ACTION = {
  type: typeof SET_DAY_SUMMARY
  payload: any[]
}
export const LOADING_REPORT = 'LOADING_REPORT'
type LOADING_REPORT_ACTION = {
  type: typeof LOADING_REPORT
}
export const STOP_LOADING_REPORT = 'STOP_LOADING_REPORT'
type STOP_LOADING_REPORT_ACTION = {
  type: typeof STOP_LOADING_REPORT
}
export const SET_DEPTH_DAY_GRAPH = 'SET_DEPTH_DAY_GRAPH'
type SET_DEPTH_DAY_GRAPH_ACTION = {
  type: typeof SET_DEPTH_DAY_GRAPH
  payload: TDepthDayGraph
}
export const SET_CALENDAR_TIME_BALANCE = 'SET_CALENDAR_TIME_BALANCE'
type SET_CALENDAR_TIME_BALANCE_ACTION = { 
  type: typeof SET_CALENDAR_TIME_BALANCE
  payload: TCalendarBalanceTime[]
}
export const SET_CALENDAR_TIME_BALANCE_DIAG = 'SET_CALENDAR_TIME_BALANCE_DIAG'
type SET_CALENDAR_TIME_BALANCE_DIAG_ACTION = {
  type: typeof SET_CALENDAR_TIME_BALANCE_DIAG
  payload: any[]
}
export const SET_CONSTRUCTOR_TIME_SHEDULE = 'SET_CONSTRUCTOR_TIME_SHEDULE'
type SET_CONSTRUCTOR_TIME_SHEDULE_ACTION = {
  type: typeof SET_CONSTRUCTOR_TIME_SHEDULE
  payload: any[]
}
export const SET_CONSTRUCTOR_TIME_SHEDULE_SHORT =
  'SET_CONSTRUCTOR_TIME_SHEDULE_SHORT'
type SET_CONSTRUCTOR_TIME_SHEDULE_SHORT_ACTION = {
  type: typeof SET_CONSTRUCTOR_TIME_SHEDULE_SHORT
  payload: any[]
}
export type REPORTS_REDUCER_ACTIONS =
  | SET_DEPTH_DAY_GRAPH_ACTION
  | LOADING_REPORT_ACTION
  | STOP_LOADING_REPORT_ACTION
  | SET_CALENDAR_TIME_BALANCE_ACTION
  | SET_CALENDAR_TIME_BALANCE_DIAG_ACTION
  | SET_CONSTRUCTOR_TIME_SHEDULE_ACTION
  | SET_CONSTRUCTOR_TIME_SHEDULE_SHORT_ACTION
  | SET_DAY_SUMMARY_ACTION
