import { TInitialState } from './types'
const initialState: TInitialState = { 
  npvActDetails: [
    {
      id: 0,
      dataField: 'docDate',
      dataType: 'string',
      caption: 'Дата',
      format: 'dd.MM.yyyy',
    },
    { id: 1, dataField: 'orderNum', dataType: 'number', caption: 'Номер' },
    {
      id: 2,
      dataField: 'workKindName',
      dataType: 'string',
      caption: 'Вид работ',
    },
    {
      id: 3,
      dataField: 'drillingRigName',
      dataType: 'string',
      caption: 'Буровая установка',
    },
    {
      id: 4,
      dataField: 'workClassifierName',
      dataType: 'string',
      caption: 'Классификатор работ БКВ',
    },
    {
      id: 5,
      dataField: 'operationDescription',
      dataType: 'string',
      caption: 'Описание операции',
    },
    {
      id: 6,
      dataField: 'startTime',
      dataType: 'string',
      caption: 'Время начала',
    },
    {
      id: 7,
      dataField: 'endTime',
      dataType: 'string',
      caption: 'Время окончания',
    },
    { id: 8, dataField: 'hours', dataType: 'number', caption: 'Кол-во часов' },
    { id: 9, dataField: 'driving', dataType: 'number', caption: 'Проходка' },
    {
      id: 10,
      dataField: 'npvDescription',
      dataType: 'string',
      caption: 'Описание НПВ',
    },
    {
      id: 11,
      dataField: 'npvCauseName',
      dataType: 'number',
      caption: 'Причина НПВ',
    },
    {
      id: 12,
      dataField: 'npvResponsibleName',
      dataType: 'string',
      caption: 'Ответственный за НПВ',
    },
    {
      id: 13,
      dataField: 'serviceName',
      dataType: 'string',
      caption: 'Наименование службы',
    },
  ],
  npvAct: [
    {
      id: 0,
      dataField: 'startDate',
      dataType: 'date',
      caption: 'Дата начала',
      format: 'dd.MM.yyyy',
    },
    {
      id: 1,
      dataField: 'endDate',
      dataType: 'date',
      caption: 'Дата окончания',
      format: 'dd.MM.yyyy',
    },
    {
      id: 2,
      dataField: 'kindName',
      dataType: 'string',
      caption: 'Наименование НПВ',
    },
    {
      id: 3,
      dataField: 'workObjectName',
      dataType: 'string',
      caption: 'Объект работ',
    },
    {
      id: 4,
      dataField: 'workResult',
      dataType: 'string',
      caption: 'Результат',
    },
    {
      id: 5,
      dataField: 'npvDescription',
      dataType: 'string',
      caption: 'Описание',
    },
  ],
  npvActKinds: [
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    {
      id: 2,
      dataField: 'isStandard',
      dataType: 'boolean',
      caption: 'Эталонный',
    },
  ],
  npvCause: [
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    { id: 1, dataField: 'orgName', dataType: 'string', caption: 'Организация' },
    {
      id: 2,
      dataField: 'isStandard',
      dataType: 'boolean',
      caption: 'Эталонный',
    },
  ],
  planDetails: [
    {
      id: 3,
      dataField: 'drillingRigName',
      dataType: 'string',
      caption: 'Буровая установка',
    },
    {
      id: 5,
      dataField: 'executorName',
      dataType: 'string',
      caption: 'Исполнитель работ',
    },
    {
      id: 11,
      dataField: 'operationMode',
      dataType: 'number',
      caption: 'Режим работы',
    },
    {
      id: 8,
      dataField: 'workKindName',
      dataType: 'string',
      caption: 'Вид работ',
    },
    {
      id: 9,
      dataField: 'startDate',
      dataType: 'date',
      caption: 'Дата начала',
      format: 'dd.MM.yyyy HH:mm',
    },
    {
      id: 10,
      dataField: 'endDate',
      dataType: 'date',
      caption: 'Дата окончания',
      format: 'dd.MM.yyyy HH:mm',
    },
    { id: 12, dataField: 'days', dataType: 'number', caption: 'Кол-во суток' },
    { id: 13, dataField: 'hours', dataType: 'number', caption: 'Кол-во часов' },
    { id: 14, dataField: 'driving', dataType: 'number', caption: 'Проходка' },
  ],
  nomenclatureTypes: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    {
      id: 1,
      dataField: 'mnemo',
      dataType: 'string',
      caption: 'Сокращённое наименование',
    },
  ],
  scenarios: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
  ],
  plans: [
    { id: 0, dataField: 'id', dataType: 'string', caption: 'Номер' },
    {
      id: 1,
      dataField: 'docDate',
      dataType: 'date',
      caption: 'Дата создания',
      format: 'dd.MM.yyyy',
    },
    {
      id: 3,
      dataField: 'scenarioName',
      dataType: 'string',
      caption: 'Сценарий',
    },

    { id: 4, dataField: 'orgName', dataType: 'string', caption: 'Организация' },
    {
      id: 5,
      dataField: 'workObjectName',
      dataType: 'string',
      caption: 'Объект работ',
    },

    { id: 2, dataField: 'comment', dataType: 'string', caption: 'Комментарий' },
    {
      id: 6,
      dataField: 'userName',
      dataType: 'string',
      caption: 'Пользователь',
    },
    { id: 7, dataField: 'statusName', dataType: 'string', caption: 'Статус' },
  ],
  unit: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
  ],
  mortarTypes: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
  ],
  nomenclature: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    {
      id: 1,
      dataField: 'mnemo',
      dataType: 'string',
      caption: 'Сокращённое наименование',
    },
    { id: 3, dataField: 'code', dataType: 'string', caption: 'Код' },
    { id: 4, dataField: 'typeName', dataType: 'string', caption: 'Тип' },
    {
      id: 5,
      dataField: 'unitName',
      dataType: 'string',
      caption: 'Единица измерения',
    },
    {
      id: 6,
      dataField: 'unitCode',
      dataType: 'string',
      caption: 'Код единицы измерения',
    },
  ],
 /*  organization: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    {
      id: 1,
      dataField: 'mnemo',
      dataType: 'string',
      caption: 'Краткое наименование',
    },
    { id: 2, dataField: 'inn', dataType: 'number', caption: 'ИНН' },
    { id: 3, dataField: 'kpp', dataType: 'number', caption: 'КПП' },
    {
      id: 4,
      dataField: 'legAddress',
      dataType: 'string',
      caption: 'Юридический адрес',
    },
    {
      id: 5,
      dataField: 'actAddress',
      dataType: 'string',
      caption: 'Фактический адрес',
    },
    { id: 6, dataField: 'email', dataType: 'string', caption: 'Почта' },
    { id: 7, dataField: 'phone', dataType: 'string', caption: 'Телефон' },
    {
      id: 8,
      dataField: 'respUserId',
      dataType: 'string',
      caption: 'Ответственный пользователь',
    },
    {
      id: 9,
      dataField: 'respEmail',
      dataType: 'string',
      caption: 'Почта ответственного',
    },
    {
      id: 10,
      dataField: 'respPhone',
      dataType: 'string',
      caption: 'Телефон ответственного',
    },
  ], */
  project: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
  ],
  user: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'login', dataType: 'string', caption: 'Логин' },
    { id: 1, dataField: 'name', dataType: 'string', caption: 'Имя' },
    {
      id: 2,
      dataField: 'contractorName',
      dataType: 'string',
      caption: 'Организация',
    },
    { id: 3, dataField: 'email', dataType: 'string', caption: 'Почта' },
    { id: 4, dataField: 'phone', dataType: 'string', caption: 'Телефон' },
    { id: 5, dataField: 'roleName', dataType: 'string', caption: 'Роль' },
  ],
  /* workClassifier: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    { id: 1, dataField: 'typeName', dataType: 'string', caption: 'Тип БКВ' },
  ], */
  /* workKind: [
    { id: 1, dataField: 'name', dataType: 'string', caption: 'Наименование' },
  ], */
  workObject: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number', 
      caption: 'Код',
      width: '150px', 
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    { id: 1, dataField: 'projectName', dataType: 'string', caption: 'Проект' },
    {
      id: 2,
      dataField: 'depositName',
      dataType: 'string',
      caption: 'Месторождение',
    },
    { id: 3, dataField: 'orgName', dataType: 'string', caption: 'Организация' },
    {
      id: 4,
      dataField: 'drillingMethod',
      dataType: 'string',
      caption: 'Способ бурения',
    },
    {
      id: 5,
      dataField: 'designedDepth',
      dataType: 'string',
      caption: 'Проектная глубина',
    },
  ],
  workObjectExecutor: [
    {
      id: 6,
      dataField: 'orgName',
      dataType: 'string',
      caption: 'Наименование',
    },
    {
      id: 7,
      dataField: 'serviceKind',
      dataType: 'string',
      caption: 'Вид сервиса',
    },
  ],
  workObjectHole: [
    { id: 8, dataField: 'diameter', dataType: 'number', caption: 'Диаметр' },
    { id: 9, dataField: 'depth', dataType: 'number', caption: 'Глубина' },
  ],
  dayliReport: [
    {
      id: 0,
      dataField: 'docNumber',
      dataType: 'string',
      caption: '№',
    },
    {
      id: 131,
      dataField: 'docDate',
      dataType: 'date',
      caption: 'Дата',
      format: 'dd.MM.yyyy',
    },
    {
      id: 6,
      dataField: 'kindName',
      dataType: 'string',
      caption: 'Вид рапорта',
    },
    {
      id: 132,
      dataField: 'employerName',
      dataType: 'string',
      caption: 'Заказчик',
    },
    {
      id: 2,
      dataField: 'workObjectName',
      dataType: 'number',
      caption: 'Объект работ',
    },
    { id: 114, dataField: 'orgName', dataType: 'number', caption: 'Подрядчик' },
    {
      id: 7,
      dataField: 'drillingRigName',
      dataType: 'string',
      caption: 'Буровая установка',
    },
    {
      id: 3,
      dataField: 'userResponsible',
      dataType: 'string',
      caption: 'Ответственный',
    },
    {
      id: 5,
      dataField: 'typeName',
      dataType: 'string',
      caption: 'Тип рапорта',
    },
    { id: 1, dataField: 'statusName', dataType: 'number', caption: 'Статус' },
    {
      id: 134,
      dataField: 'userConfirmed',
      dataType: 'string',
      caption: 'Подтвердил',
    },
    { id: 4, dataField: 'comment', dataType: 'string', caption: 'Комментарий' },
  ],
  dr_tech_operations: [
    {
      id: 6,
      dataField: 'workKindName',
      dataType: 'string',
      caption: 'Вид работ',
    },
    {
      id: 8,
      dataField: 'classifierName',
      dataType: 'string',
      caption: 'Классификатор работ БКВ',
    },
    {
      id: 9,
      dataField: 'npvResponsibleName',
      dataType: 'string',
      caption: 'Ответственный на НПВ',
    },
    {
      id: 10,
      dataField: 'startTime',
      dataType: 'datetime',
      caption: 'Время начала',
      format: 'HH:mm',
    },
    {
      id: 11,
      dataField: 'endTime',
      dataType: 'datetime',
      caption: 'Время окончания',
      format: 'HH:mm',
    },
    { id: 12, dataField: 'driving', dataType: 'number', caption: 'Проходка' },
    {
      id: 13,
      dataField: 'npvDescription',
      dataType: 'string',
      caption: 'Описание НПВ',
    },
    {
      id: 14,
      dataField: 'serviceName',
      dataType: 'string',
      caption: 'Наименование сервиса',
    },
    {
      id: 15,
      dataField: 'operDescription',
      dataType: 'string',
      caption: 'Описание операции',
    },
  ],
  dr_knbk: [
    { id: 16, dataField: 'tripNumber', dataType: 'number', caption: '№ рейса' },
    {
      id: 17,
      dataField: 'knbkElement',
      dataType: 'string',
      caption: 'Элемент КНБК',
    },
    {
      id: 18,
      dataField: 'externalD',
      dataType: 'number',
      caption: 'Ø нар, мм',
    },
    { id: 19, dataField: 'internalD', dataType: 'number', caption: 'Ø вн, мм' },
    {
      id: 20,
      dataField: 'quantity',
      dataType: 'number',
      caption: 'Кол-во (шт)',
    },
    { id: 21, dataField: 'length', dataType: 'number', caption: 'Длина (м)' },
    { id: 22, dataField: 'totalLength', dataType: 'number', caption: 'Σ, м' },
    { id: 23, dataField: 'mass', dataType: 'number', caption: 'Масса (кг)' },
    { id: 24, dataField: 'totalMass', dataType: 'number', caption: 'Σ, кг' },
  ],
  dr_chisel: [
    { id: 25, dataField: 'tripNumber', dataType: 'number', caption: '№ рейса' },
    { id: 26, dataField: 'externalD', dataType: 'number', caption: 'Ø, мм' },
    { id: 27, dataField: 'chiselModel', dataType: 'string', caption: 'Модель' },
    {
      id: 28,
      dataField: 'iadcCode',
      dataType: 'string',
      caption: 'Код по IADC',
    },
    {
      id: 29,
      dataField: 'chiselNumber',
      dataType: 'number',
      caption: '№ долота',
    },
    { id: 30, dataField: 'turns', dataType: 'number', caption: 'Об/мин' },
    {
      id: 31,
      dataField: 'load',
      dataType: 'number',
      caption: 'Нагрузка, тонн',
    },
    { id: 32, dataField: 'feed', dataType: 'number', caption: 'Q, л/сек' },
    {
      id: 33,
      dataField: 'startInterval',
      dataType: 'number',
      caption: 'Интервал  бурения от, м',
    },
    {
      id: 34,
      dataField: 'endInterval',
      dataType: 'number',
      caption: 'Интервал бурения до, м',
    },
    { id: 35, dataField: 'pressure', dataType: 'number', caption: 'P, Атм' },
    {
      id: 36,
      dataField: 'drillingTime',
      dataType: 'number',
      caption: 'Время бур сут, ч',
    },
    {
      id: 37,
      dataField: 'mechSpeed',
      dataType: 'number',
      caption: 'Vмех, м/час',
    },
    {
      id: 38,
      dataField: 'workCode',
      dataType: 'string',
      caption: 'Отработка по коду',
    },
    { id: 39, dataField: 'note', dataType: 'string', caption: 'Примечание' },
  ],
  dr_drill_mortar: [
    {
      id: 41,
      dataField: 'measureTime',
      dataType: 'datetime',
      caption: 'Время замера',
      format: 'HH:mm',
    },
    { id: 59, dataField: 'typeName', dataType: 'string', caption: 'Тип' },
    { id: 42, dataField: 'y', dataType: 'string', caption: 'Y, г/см3' },
    { id: 43, dataField: 't', dataType: 'string', caption: 'Т, сек' },
    { id: 44, dataField: 'f', dataType: 'string', caption: 'Ф, см3/30 мин' },
    { id: 45, dataField: 'crust', dataType: 'string', caption: 'Корка, мм' },
    { id: 46, dataField: 'ph', dataType: 'string', caption: 'рН' },
    { id: 47, dataField: 'sns', dataType: 'string', caption: 'СНС, дПа' },
    { id: 48, dataField: 'dns', dataType: 'string', caption: 'ДНС, дПа' },
    {
      id: 49,
      dataField: 'viscocity',
      dataType: 'string',
      caption: 'Пл. вязкость, мПа*с',
    },
    { id: 50, dataField: 'ktk', dataType: 'string', caption: 'КТК' },
    { id: 51, dataField: 'sand', dataType: 'string', caption: 'Песок, %' },
    {
      id: 52,
      dataField: 'solidPhase',
      dataType: 'string',
      caption: 'Твердая фаза, %',
    },
    { id: 53, dataField: 'mvt', dataType: 'string', caption: 'МВТ' },
    {
      id: 54,
      dataField: 'filtrateDensity',
      dataType: 'string',
      caption: 'Плотность фильтрата',
    },
    { id: 55, dataField: 'chl', dataType: 'string', caption: 'Cl' },
    { id: 56, dataField: 'cal', dataType: 'string', caption: 'Ca' },
    { id: 57, dataField: 'es', dataType: 'string', caption: 'Э/С' },
    { id: 58, dataField: 'note', dataType: 'string', caption: 'Примечание' },
  ],
  dr_drill_mortar_volume: [
    {
      id: 74,
      dataField: 'measureTime',
      dataType: 'datetime',
      caption: 'Время замера',
    },
    { id: 60, dataField: 'gage1', dataType: 'number', caption: 'Мерник-1' },
    { id: 61, dataField: 'gage2', dataType: 'number', caption: 'Мерник-2' },
    { id: 62, dataField: 'gage3', dataType: 'number', caption: 'Мерник-3' },
    { id: 63, dataField: 'gage4', dataType: 'number', caption: 'Мерник-4' },
    { id: 64, dataField: 'gage5', dataType: 'number', caption: 'Мерник-5' },
    { id: 65, dataField: 'bpr', dataType: 'number', caption: 'БПР' },
    { id: 67, dataField: 'bde', dataType: 'number', caption: 'БДЕ' },
    { id: 68, dataField: 'ca', dataType: 'number', caption: 'ЦА' },
    { id: 69, dataField: 'inHole', dataType: 'number', caption: 'В скважине' },
    { id: 70, dataField: 'csgo', dataType: 'number', caption: 'ЦСГО' },
    { id: 71, dataField: 'popping', dataType: 'number', caption: 'Долив' },
    {
      id: 72,
      dataField: 'onSurface',
      dataType: 'number',
      caption: 'На поверхности',
    },
    { id: 73, dataField: 'total', dataType: 'number', caption: 'Итого' },
  ],
  dr_drill_mortar_loss: [
    {
      id: 74,
      dataField: 'measureTime',
      dataType: 'datetime',
      caption: 'Время замера',
    },
    {
      id: 75,
      dataField: 'complication',
      dataType: 'number',
      caption: 'Осложн',
    },
    { id: 76, dataField: 'recess', dataType: 'number', caption: 'Углубл' },
    { id: 77, dataField: 'spo', dataType: 'number', caption: 'СПО' },
    { id: 78, dataField: 'cleaning', dataType: 'number', caption: 'Очистка' },
    { id: 79, dataField: 'other', dataType: 'number', caption: 'Прочее' },
    {
      id: 80,
      dataField: 'filtration',
      dataType: 'number',
      caption: 'Фильтрация',
    },
    { id: 81, dataField: 'dump', dataType: 'number', caption: 'Сброс' },
  ],
  dr_clean_system_work: [
    { id: 83, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 84,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    { id: 85, dataField: 'state', dataType: 'boolean', caption: 'Состояние' },
    {
      id: 86,
      dataField: 'workHours',
      dataType: 'number',
      caption: 'Время работы за сут.',
    },
    { id: 87, dataField: 'status', dataType: 'string', caption: 'Статус' },
  ],
  dr_drill_pump_work: [
    { id: 88, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 89,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    { id: 90, dataField: 'sleeveD', dataType: 'number', caption: 'Ø, втулок' },
    { id: 91, dataField: 'moveCount', dataType: 'number', caption: 'Ходы' },
    { id: 92, dataField: 'feed', dataType: 'number', caption: 'Q, л/сек' },
    { id: 93, dataField: 'pressure', dataType: 'number', caption: 'Р, Атм' },
  ],
  dr_breakdown_instrument: [
    { id: 94, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 95,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    {
      id: 96,
      dataField: 'hasPassport',
      dataType: 'boolean',
      caption: 'Паспорт',
    },
    {
      id: 97,
      dataField: 'startQuantity',
      dataType: 'number',
      caption: 'Кол-во (на начало)',
    },
    {
      id: 98,
      dataField: 'incomeQuantity',
      dataType: 'number',
      caption: 'Кол-во (приход)',
    },
    {
      id: 99,
      dataField: 'expenditureQuantity',
      dataType: 'number',
      caption: 'Кол-во (расход)',
    },
    {
      id: 100,
      dataField: 'endQuantity',
      dataType: 'number',
      caption: 'Кол-во (остаток)',
    },
  ],
  dr_material_consumption: [
    { id: 101, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 102,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    { id: 103, dataField: 'unitName', dataType: 'string', caption: 'Ед. изм.' },
    {
      id: 104,
      dataField: 'startQuantity',
      dataType: 'number',
      caption: 'Кол-во (на начало)',
    },
    {
      id: 105,
      dataField: 'incomeQuantity',
      dataType: 'number',
      caption: 'Кол-во (приход)',
    },
    {
      id: 106,
      dataField: 'expenditureQuantity',
      dataType: 'number',
      caption: 'Кол-во (расход)',
    },
    {
      id: 107,
      dataField: 'endQuantity',
      dataType: 'number',
      caption: 'Кол-во (остаток)',
    },
  ],
  dr_drill_mortar_prep: [
    {
      id: 108,
      dataField: 'measureTime',
      dataType: 'datetime',
      caption: 'Время замера',
    },
    { id: 109, dataField: 'gage1', dataType: 'number', caption: 'Мерник-1' },
    { id: 110, dataField: 'gage2', dataType: 'number', caption: 'Мерник-2' },
    { id: 111, dataField: 'gage3', dataType: 'number', caption: 'Мерник-3' },
    { id: 112, dataField: 'gage4', dataType: 'number', caption: 'Мерник-4' },
    { id: 113, dataField: 'gage5', dataType: 'number', caption: 'Мерник-5' },
    { id: 114, dataField: 'bpr', dataType: 'number', caption: 'БПР' },
    { id: 115, dataField: 'bde', dataType: 'number', caption: 'БДЕ' },
    { id: 116, dataField: 'ca', dataType: 'number', caption: 'ЦА' },
    { id: 117, dataField: 'inHole', dataType: 'number', caption: 'В скважине' },
    { id: 118, dataField: 'csgo', dataType: 'number', caption: 'ЦСГО' },
    { id: 119, dataField: 'popping', dataType: 'number', caption: 'Долив' },
    {
      id: 120,
      dataField: 'onSurface',
      dataType: 'number',
      caption: 'На поверхности',
    },
    { id: 121, dataField: 'total', dataType: 'number', caption: 'Итого' },
  ],
  dr_disel_consumption: [
    { id: 122, dataField: 'orderNum', dataType: 'string', caption: '№ п/п' },
    {
      id: 123,
      dataField: 'consumer',
      dataType: 'string',
      caption: 'Потребитель',
    },
    {
      id: 124,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    { id: 125, dataField: 'unitName', dataType: 'string', caption: 'Ед. изм.' },
    { id: 126, dataField: 'quantity', dataType: 'number', caption: 'Кол-во' },
    {
      id: 127,
      dataField: 'total',
      dataType: 'number',
      caption: 'Всего (с нач. работ)',
    },
  ],
  dr_chisel_drill_head: [
    { id: 128, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 129,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    {
      id: 130,
      dataField: 'factoryNumber',
      dataType: 'string',
      caption: 'Зав. № долота',
    },
    {
      id: 131,
      dataField: 'startQuantity',
      dataType: 'number',
      caption: 'Кол-во (на начало)',
    },
    {
      id: 132,
      dataField: 'incomeQuantity',
      dataType: 'number',
      caption: 'Кол-во (приход)',
    },
    {
      id: 133,
      dataField: 'expenditureQuantity',
      dataType: 'number',
      caption: 'Кол-во (расход)',
    },
    {
      id: 134,
      dataField: 'endQuantity',
      dataType: 'number',
      caption: 'Кол-во (остаток)',
    },
  ],
  dr_tech_gear: [
    { id: 135, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 136,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    { id: 137, dataField: 'unitName', dataType: 'string', caption: 'Ед. изм.' },
    {
      id: 138,
      dataField: 'startQuantity',
      dataType: 'number',
      caption: 'Кол-во (на начало)',
    },
    {
      id: 139,
      dataField: 'incomeQuantity',
      dataType: 'number',
      caption: 'Кол-во (приход)',
    },
    {
      id: 140,
      dataField: 'expenditureQuantity',
      dataType: 'number',
      caption: 'Кол-во (расход)',
    },
    {
      id: 141,
      dataField: 'endQuantity',
      dataType: 'number',
      caption: 'Кол-во (остаток)',
    },
  ],
  dr_casing_nkt: [
    { id: 142, dataField: 'orderNumber', dataType: 'number', caption: '№ п/п' },
    {
      id: 143,
      dataField: 'nomName',
      dataType: 'number',
      caption: 'Номенклатура',
    },
    { id: 144, dataField: 'externalD', dataType: 'number', caption: 'Ø нар' },
    { id: 145, dataField: 'wallThickness', dataType: 'number', caption: 'Тст' },
    {
      id: 146,
      dataField: 'firmnessGroup',
      dataType: 'string',
      caption: 'Гр. прочности',
    },
    {
      id: 147,
      dataField: 'threadType',
      dataType: 'string',
      caption: 'Тип резьбового соединения',
    },
    {
      id: 148,
      dataField: 'startQuantityP',
      dataType: 'number',
      caption: 'Кол-во на начало (шт.)',
    },
    {
      id: 149,
      dataField: 'startQuantityM',
      dataType: 'number',
      caption: 'Кол-во  на начало (м)',
    },
    {
      id: 150,
      dataField: 'incomeQuantityP',
      dataType: 'number',
      caption: 'Кол-во приход (шт.)',
    },
    {
      id: 151,
      dataField: 'incomeQuantityM',
      dataType: 'number',
      caption: 'Кол-во приход (м)',
    },
    {
      id: 152,
      dataField: 'expendQuantityP',
      dataType: 'number',
      caption: 'Кол-во расход (шт.)',
    },
    {
      id: 153,
      dataField: 'expendQuantityM',
      dataType: 'number',
      caption: 'Кол-во расход (м)',
    },
    {
      id: 154,
      dataField: 'defectP',
      dataType: 'number',
      caption: 'Брак (шт.)',
    },
    { id: 155, dataField: 'defectM', dataType: 'number', caption: 'Брак (м)' },
    {
      id: 156,
      dataField: 'defectNote',
      dataType: 'string',
      caption: 'Брак (примечание)',
    },
    {
      id: 157,
      dataField: 'endQuantityP',
      dataType: 'number',
      caption: 'Кол-во остаток (шт.)',
    },
    {
      id: 158,
      dataField: 'endQuantityM',
      dataType: 'number',
      caption: 'Кол-во остаток (м)',
    },
  ],
  dr_drill_instrument_knbk_elements: [
    { id: 159, dataField: 'orderNumber', dataType: 'number', caption: '№ п/п' },
    {
      id: 160,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    { id: 162, dataField: 'externalD', dataType: 'number', caption: 'Øвн.' },
    { id: 163, dataField: 'internalD', dataType: 'number', caption: 'Øвн.' },
    {
      id: 164,
      dataField: 'firmnessGroup',
      dataType: 'string',
      caption: 'Гр. пр. /м. стали',
    },
    {
      id: 165,
      dataField: 'startQP',
      dataType: 'number',
      caption: 'Кол-во на начало (шт.)',
    },
    {
      id: 166,
      dataField: 'startQM',
      dataType: 'number',
      caption: 'Кол-во на начало (м)',
    },
    {
      id: 167,
      dataField: 'startQT',
      dataType: 'number',
      caption: 'Кол-во на начало (тн)',
    },
    {
      id: 168,
      dataField: 'incomeQP',
      dataType: 'number',
      caption: 'Кол-во приход (шт.)',
    },
    {
      id: 169,
      dataField: 'incomeQM',
      dataType: 'number',
      caption: 'Кол-во приход (м)',
    },
    {
      id: 170,
      dataField: 'incomeQT',
      dataType: 'number',
      caption: 'Кол-во приход (тн)',
    },
    {
      id: 171,
      dataField: 'expendQP',
      dataType: 'number',
      caption: 'Кол-во расход (шт.)',
    },
    {
      id: 172,
      dataField: 'expendQM',
      dataType: 'number',
      caption: 'Кол-во расход (м)',
    },
    {
      id: 173,
      dataField: 'expendQT',
      dataType: 'number',
      caption: 'Кол-во расход (тн)',
    },
    {
      id: 174,
      dataField: 'endQP',
      dataType: 'number',
      caption: 'Кол-во на конец (шт.)',
    },
    {
      id: 175,
      dataField: 'endQM',
      dataType: 'number',
      caption: 'Кол-во на конец (м)',
    },
    {
      id: 176,
      dataField: 'endQT',
      dataType: 'number',
      caption: 'Кол-во на конец (тн)',
    },
    {
      id: 177,
      dataField: 'runningTime',
      dataType: 'number',
      caption: 'Наработка (часов)',
    },
    {
      id: 178,
      dataField: 'runningTimeStart',
      dataType: 'number',
      caption: 'Наработка (часов) с начала работ',
    },
    {
      id: 179,
      dataField: 'defectoscopyDate',
      dataType: 'date',
      caption: 'Дата дефектоскопии',
      format: 'dd.MM.yyyy',
    },
  ],
  dr_tech_equipment: [
    {
      id: 180,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    {
      id: 181,
      dataField: 'hasPassport',
      dataType: 'boolean',
      caption: 'Паспорт',
    },
    {
      id: 182,
      dataField: 'startQ',
      dataType: 'number',
      caption: 'Кол-во (на начало)',
    },
    {
      id: 183,
      dataField: 'incomeQ',
      dataType: 'number',
      caption: 'Кол-во (приход)',
    },
    {
      id: 184,
      dataField: 'expendQ',
      dataType: 'number',
      caption: 'Кол-во (расход)',
    },
    {
      id: 185,
      dataField: 'endQ',
      dataType: 'number',
      caption: 'Кол-во (остаток)',
    },
  ],
  dr_work_line: [
    { id: 186, dataField: 'orderNum', dataType: 'string', caption: '№ п/п' },
    {
      id: 187,
      dataField: 'diameter',
      dataType: 'number',
      caption: 'Диаметр, мм',
    },
    {
      id: 188,
      dataField: 'installDate',
      dataType: 'date',
      caption: 'Дата установки',
      format: 'dd.MM.yyyy',
    },
    {
      id: 189,
      dataField: 'coilLength',
      dataType: 'number',
      caption: 'Длина в бухте, м',
    },
    { id: 190, dataField: 'tooling', dataType: 'string', caption: 'Оснастка' },
    {
      id: 191,
      dataField: 'overwindDate',
      dataType: 'date',
      caption: 'Перетяжка, дата',
      format: 'dd.MM.yyyy',
    },
    {
      id: 192,
      dataField: 'overwindOperating',
      dataType: 'number',
      caption: 'Перетяжка, при наработке (м)',
    },
    {
      id: 193,
      dataField: 'overwindLength',
      dataType: 'number',
      caption: 'Перетяжка, м',
    },
    {
      id: 194,
      dataField: 'runningTimeSensor',
      dataType: 'number',
      caption: 'Наработка за рейс, датчик',
    },
    {
      id: 195,
      dataField: 'runningTmeEstim',
      dataType: 'number',
      caption: 'Наработка за рейс, расчет',
    },
    {
      id: 196,
      dataField: 'runningTimeSensorTotal',
      dataType: 'number',
      caption: 'Наработка за рейс, Σ датчик',
    },
    {
      id: 197,
      dataField: 'runningTimeEstimTotal',
      dataType: 'number',
      caption: 'Остаток в бухте',
    },
  ],
  dr_diesel_work: [
    { id: 198, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 199,
      dataField: 'nomName',
      dataType: 'string',
      caption: 'Номенклатура',
    },
    {
      id: 200,
      dataField: 'factoryNumber',
      dataType: 'number',
      caption: 'Зав. №',
    },
    {
      id: 201,
      dataField: 'run',
      dataType: 'number',
      caption: 'Наработка (маш./час)',
    },
    {
      id: 202,
      dataField: 'monthRun',
      dataType: 'number',
      caption: 'Наработка (маш./час)  месяц',
    },
    {
      id: 203,
      dataField: 'totalRun',
      dataType: 'number',
      caption: 'Наработка (маш./час) с начала работ',
    },
    { id: 204, dataField: 'state', dataType: 'string', caption: 'Состояние' },
  ],
  dr_staff: [
    { id: 206, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 205,
      dataField: 'orgName',
      dataType: 'string',
      caption: 'Организация-работодатель',
    },
    {
      id: 205,
      dataField: 'position',
      dataType: 'string',
      caption: 'Должность',
    },
    { id: 205, dataField: 'name', dataType: 'string', caption: 'ФИО' },
    {
      id: 205,
      dataField: 'hours',
      dataType: 'string',
      caption: 'Кол-во часов',
    },
  ],
  dr_special_machine_work: [
    { id: 207, dataField: 'orderNum', dataType: 'number', caption: '№ п/п' },
    {
      id: 207,
      dataField: 'nomName',
      dataType: 'number',
      caption: 'Номенклатура',
    },
    {
      id: 207,
      dataField: 'stateNumber',
      dataType: 'string',
      caption: 'Гос. Номер',
    },
    {
      id: 207,
      dataField: 'driverName',
      dataType: 'string',
      caption: 'Водитель',
    },
    { id: 207, dataField: 'work', dataType: 'number', caption: 'Работа, час' },
    {
      id: 207,
      dataField: 'duty',
      dataType: 'number',
      caption: 'Дежурство, час',
    },
    {
      id: 207,
      dataField: 'repair',
      dataType: 'number',
      caption: 'Ремонт, час',
    },
    {
      id: 207,
      dataField: 'sediment',
      dataType: 'number',
      caption: 'Отстой, час',
    },
    { id: 207, dataField: 'note', dataType: 'string', caption: 'Примечание' },
    {
      id: 207,
      dataField: 'description',
      dataType: 'string',
      caption: 'Описание выполняемых работ',
    },
  ],
  /* drillingRig: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
  ], */
  /* contract: [
    { id: 0, dataField: 'statusName', dataType: 'string', caption: 'Статус' },
    {
      id: 1,
      dataField: 'docDate',
      dataType: 'date',
      caption: 'Дата создания',
      format: 'dd.MM.yyyy',
    },
    { id: 2, dataField: 'name', dataType: 'string', caption: 'Наименование' },
    {
      id: 3,
      dataField: 'executorName',
      dataType: 'string',
      caption: 'Подрядчик',
    },
    {
      id: 4,
      dataField: 'workObjectName',
      dataType: 'string',
      caption: 'Объект работ',
    },
  ], */
  /* contractDetails: [
    {
      id: 4,
      dataField: 'workObjectName',
      dataType: 'string',
      caption: 'Объект работ',
    },
    {
      id: 5,
      dataField: 'workKindName',
      dataType: 'string',
      caption: 'Вид работ',
    },
    {
      id: 6,
      dataField: 'startDate',
      dataType: 'date',
      caption: 'Дата начала',
      format: 'dd.MM.yyyy',
    },
    {
      id: 7,
      dataField: 'endDate',
      dataType: 'date',
      caption: 'Дата окончания',
      format: 'dd.MM.yyyy',
    },
  ], */
  deposit: [
    {
      id: 100,
      dataField: 'id',
      dataType: 'number',
      caption: 'Код',
      width: '150px',
    },
    { id: 0, dataField: 'name', dataType: 'string', caption: 'Наименование' },
  ],
}

export const columnsReducer = (state = initialState, action: any): TInitialState => {
  switch (action.type) {
    default:
      return state
  }
}
